### ISSUE TITLE
Option --enable-create-dirs fails with chroot builds

### ISSUE THREAD

**Issue by aabdnn** [DNS-OARC/dsp#17]
If I pass --enable-create-dirs to the configure script, then the resulting Makefile tries to create:

/var/log/dsp
/var/lib/dsc
/var/cache/dsp

It doesn't prepend them with DESTDIR, so if I'm building an RPM package in a chroot, then it fails, because non-root users can't create these directories.

**Comment by jelu** [comment]
That option is not really meant to be used in packages, it was added to make the installation compatible with how it worked before the FHS changes.

You should be able to create these directories in the SPEC of the RPM right?

**Comment by aabdnn** [comment]
Yes, sure. I can create the directories in the SPEC file, and then package them up. But in my opinion, if you have the option, and a packager decides to use it, then it should not cause the build to fail. A packager shouldn't have to know that the option is only for use in certain special cases.

Even if I put the packaging issue aside for a moment, the use of this option still causes build failures in the case that a user is doing a root-less installation in his home directory, for example. Therefore, I still think that the option should do the correct thing by creating these directories relative to DESTDIR, just like all the others.

**Comment by jelu** [comment]
Try my `destdir` branch, unsure if this fixes all cases.

```
git clone https://github.com/jelu/dsp.git
cd dsp
git checkout destdir
```

**Comment by jelu** [comment]
@aabdnn ping?

**Comment by jelu** [comment]
@aabdnn ping?
