### ISSUE TITLE
DSC and DSP multi node installation

### ISSUE THREAD

**Issue by maileh** [DNS-OARC/dsp#18]
Hi
Could someone give any detail regarding the installation of muliple collector node and a central node which present the data from the collector. I look in to several notes but i could not figure out how to install the dsp to recieve the data from the collector and present it. Really appreciate any kind feedback on this.
Thaks in advance.
Maile

**Comment by maileh** [comment]
In Addition to my issue above.
I follow this list https://github.com/DNS-OARC/dsp/wiki/Multi-Node-Setup-Guide#setup-nginx-and-fastcgi but it use nginx while i use apache. Can someone point to where apache is used instead of nginx.... thanks

**Comment by jelu** [comment]
Did you read https://github.com/DNS-OARC/dsp/wiki/Multi-Node-Setup-Guide#final-touches ?

For help setting to FastCGI on Apache there is plenty of online documentation:
https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html
https://wiki.apache.org/httpd/HelpOnInstalling/FastCgi
http://askubuntu.com/questions/378734/how-to-configure-apache-to-run-php-as-fastcgi-on-ubuntu-12-04-via-terminal

**Comment by maileh** [comment]
@jelu 
Thsnks for your time and your prompt reply ... i manage to figure it out ...
My issue now is that after transferring xml data from collector to the presenter when i load the webpage it says no data available, also when i checked on the NODE folder where i transferred data to , no more xml files in there ... did i miss something or do wrong ... really appreciate your kind reply

**Comment by jelu** [comment]
Let's keep this in one channel, answering the email.
